name: Release (macOS)

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*"

jobs:
  release-macos:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build (webpack)
        run: npm run build

      - name: Publish macOS DMG to GitHub Releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --mac dmg --publish always

      - name: Upload build artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifacts
          path: |
            release/*.dmg
            release/*.zip
            release/latest-mac.yml
name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g. 1.0.0)'
        required: true
        default: '1.0.0'

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create or update GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}
          name: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}
          generateReleaseNotes: true
          makeLatest: true
          allowUpdates: true

