name: release-electron-dmg

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: macos-13
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Sync app version from tag
        run: |
          node -e "const fs=require('fs');const p=require('./package.json');const tag=process.env.TAG||'';const v=tag.replace(/^v/,'');p.version=v;fs.writeFileSync('package.json', JSON.stringify(p,null,2));console.log('Set version to', v);" \
            && head -n 10 package.json
        env:
          TAG: ${{ github.ref_name }}

      - name: Build webpack artifacts
        run: npm run build

      - name: Build mac dmg and publish to GitHub Release
        run: npx electron-builder --mac dmg --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # (옵션) 코드서명/공증 필요 시 아래 시크릿을 저장하고 주석 해제하세요.
          # APPLE_ID: ${{ secrets.APPLE_ID }}
          # APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          # APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          # CSC_LINK: ${{ secrets.MAC_CERT_P12_BASE64 }}
          # CSC_KEY_PASSWORD: ${{ secrets.MAC_CERT_PASSWORD }}